### ISSUE TITLE
'role-name' is in skip_list, but is not being skipped

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-compat#78] opened 2021-09-19 05:41 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible [core 2.11.5] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jgeerling/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.5 (default, May  3 2021, 19:12:05) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
molecule 3.5.1 using python 3.9 
    ansible:2.11.5
    delegated:3.5.1 from molecule
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

N/A

# Desired Behavior

I have the following `.ansible-lint` file set up:

```yaml
skip_list:
  - 'yaml'
  - 'role-name'
```

When I run `molecule test` on any of my roles named with dashes (which are grandfathered in on Galaxy) like `geerlingguy.aws-inspector` (role here: https://github.com/geerlingguy/ansible-role-aws-inspector), I get the error:

```
ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of geerlingguy.aws-inspector does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.
```

`skip_list` should work as documented, and it _has_ until today. It seems like something in the ability to skip the `role-name` check has changed and now all my roles like the one linked above are failing to run in Molecule :(

# Actual Behaviour

See above—if I run `molecule test` inside the repo for `geerlingguy.aws-inspector` (or any other role I have with a dash in the name), I get a fail immediately with the same error message.

**Comment by briantist** [comment] 2021-10-01 15:47
I also just got bit by this. It happens in prerun and isn't related to what's set in `lint:` on molecule's config (that threw me off too).

**Comment by ssbarnea** [comment] 2021-10-01 16:06
@briantist if you could also post a link to a repo, it will make it easier to reproduce/fix.

**Comment by briantist** [comment] 2021-10-01 16:10
> @briantist if you could also post a link to a repo, it will make it easier to reproduce/fix.

I would but unfortunately this is an internal repo/collection/CI.

I can share that my `.config/molecule/config.yml` contains a lint entry like this:
```yaml
lint: |
  set -e
  ansible-lint -c ../../.ansible-lint
```
But even removing that, the error remains.

Unlike normal runs of molecule, where it gets to the dependency step and then the lint step, this error occurs before even getting to the dependency step.

My slightly redacted output looks like this:
```
[2021-10-01T14:33:39.699Z] + molecule test --parallel --all

[2021-10-01T14:33:40.001Z] INFO     Found config file /home/ubuntu/workspace/****/****/ns.coll/.config/molecule/config.yml

[2021-10-01T14:33:40.301Z] INFO     Performing prerun...

[2021-10-01T14:33:40.301Z] INFO     Added ANSIBLE_LIBRARY=/root/.cache/ansible-compat/ec731c/modules:/root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules

[2021-10-01T14:33:40.605Z] INFO     Added ANSIBLE_COLLECTIONS_PATHS=/root/.cache/ansible-compat/ec731c/collections:/root/.ansible/collections:/usr/share/ansible/collections

[2021-10-01T14:33:40.605Z] INFO     Added ANSIBLE_ROLES_PATH=/root/.cache/ansible-compat/ec731c/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles

[2021-10-01T14:33:40.605Z] ERROR    Computed fully qualified role name of john.smith.auth does not follow current galaxy requirements.

[2021-10-01T14:33:40.605Z] Please edit meta/main.yml and assure we can correctly determine full role name:
```

If there's anything else I could provide, let me know and I will try to get it, but I think you won't need much to reproduce this, just any role that fails a default lint rule.

**Comment by nikaro** [comment] 2021-10-15 18:49
Workaround that worked for me:

```patch
diff --git a/meta/main.yml b/meta/main.yml
index 97f7b74..ee588a7 100644
--- a/meta/main.yml
+++ b/meta/main.yml
@@ -2,6 +2,7 @@

 galaxy_info:
   role_name: "zfs"
+  namespace: "atexo"
   description: "zfs"
   author: "Atexo"
   company: "Atexo"
```

**Comment by moinulrony** [comment] 2021-11-19 05:03
Bumped into the issue while playing up with Molecule. 

Just put a namespace entry in the fresh install of molecule role meta/main.yml file as following example.

galaxy_info:
  role_name: blabla
  namespace: yourloginname
  
Then run molecule test and it should work fine.

**Comment by geerlingguy** [comment] 2021-11-19 17:07
@moinulrony - I'm still running into this for all my roles with names like `role-name` (note the dash in the name).

**Comment by greg-hellings** [comment] 2021-11-19 17:18
Have you guys tried the latest development head of Molecule? The main branch should contain an existing fix for this (at least it does for me, which is why I put it in there 😂). It would be good to see if it solved this problem more broadly.

It doesn't specifically address why the rule is not being skipped, but it does a better job of detecting collection behavior which is at least the problem for some on this thread.

**Comment by mrlesmithjr** [comment] 2021-11-22 19:04
Definitely running into this issue as well. Thanks, @cityofships for linking to this.

**Comment by plemelin** [comment] 2021-11-26 19:04
@greg-hellings Does not seem to be doing anything:

```
#molecule --version
molecule 3.5.3.dev31 using python 3.9 
    ansible:2.12.0
    delegated:3.5.3.dev31 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

Installed with: 
```
#pip install --upgrade git+https://github.com/ansible-community/molecule.git
```

Still get 
```
#molecule create   
INFO     default scenario test matrix: dependency, create, prepare
INFO     Performing prerun...
INFO     Added ANSIBLE_LIBRARY=/home/palemelin/.cache/ansible-compat/450300/modules:/home/palemelin/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Added ANSIBLE_COLLECTIONS_PATH=/home/palemelin/.cache/ansible-compat/450300/collections:/home/palemelin/.ansible/collections:/usr/share/ansible/collections
INFO     Added ANSIBLE_ROLES_PATH=/home/palemelin/.cache/ansible-compat/450300/roles:/home/palemelin/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
ERROR    Computed fully qualified role name of redacted.old-role-with-dashes does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.
```

My `.ansible-lint`

```
#cat .ansible-lint 
skip_list:
  - 'yaml'
  - 'role-name'
```

My `meta/main.yml`:
```
---
dependencies:
galaxy_info:
  role_name: old-role-with-dashes
  namespace: redacted
```


---
Also..

Why is the top google link for this issue linking to the trash ~issueexplorer.com~ website is beyond me. 
Search for the exact title of this ticket does not lead to this issue on GitHub, i am therefor dropping the URL here: https://github.com/ansible-community/ansible-compat/issues/78 -- `https://github.com/ansible-community/ansible-compat/issues/78`

**Comment by PhilippSelenium** [comment] 2021-12-21 15:07
> Bumped into the issue while playing up with Molecule.
> 
> Just put a namespace entry in the fresh install of molecule role meta/main.yml file as following example.
> 
> galaxy_info: role_name: blabla namespace: yourloginname
> 
> Then run molecule test and it should work fine.

I do not want to add a useless namespace to all of my 30+ roles, is there any update on this?

**Comment by ssbarnea** [comment] 2021-12-29 12:08
@PhilippSelenium I am afraid that there will be no workaround for this issue if your roles are originating from another repository. There are too many problems related to that and if we do allow it we will prevent our tooling from working correctly and spotting real bugs for users that are following the official guidelines.

Just to give one example: if you have a role named `foo` and you are publishing it under `acme`, you will need to use `acme.foo` when you include it, otherwise you will risk importing another `foo` role. Shadowing is a real source of problems and we want to avoid it.

PS. I am not against a backwards compatibility mode but considering the lack of contributions, I doubt I will see it soon.

**Comment by PhilippSelenium** [comment] 2021-12-29 12:35
@ssbarnea I don't think you got my point: My original [issue](https://github.com/ansible-community/molecule/issues/3336) was that I cannot disable these checks using the .ansible-lint skip-list directive.

I totally agree that the default should be as is and throw the error/warning but it should also be possible to ignore the error/warning if needed.

I also do not see that as a workaround but a bug fix. For me the workaround is adding namespaces ;)

**Comment by ssbarnea** [comment] 2021-12-29 12:38
@PhilippSelenium Ahh... yep adding namespaces is the best workaround IMHO.

**Comment by PhilippSelenium** [comment] 2021-12-29 12:48
@ssbarnea So you don't think that an ignored skip-list entry is a bug or that the bug will not be fixed?

**Comment by ssbarnea** [comment] 2022-03-07 16:00
@geerlingguy Send me link to one of the these projects and I will try to find something. It is bit tricky because a collection cannot have roles with invalid names. You cannot install it. Still, I will see if I can add something to unblock you, like you said buying some time so you can migrate.

**Comment by geerlingguy** [comment] 2022-03-07 17:03
@ssbarnea - https://github.com/geerlingguy/ansible-role-php-xhprof/runs/5450881278?check_suite_focus=true#step:5:15 is one—I have `role-name` in skip_list (https://github.com/geerlingguy/ansible-role-php-xhprof/blob/master/.ansible-lint#L3), but when I run `molecule test` on it, it spits out the error that I should add `role-name` to my skip_list (even though it's already there).

**Comment by briantist** [comment] 2022-03-07 19:48
> https://github.com/geerlingguy/ansible-role-php-xhprof/runs/5450881278?check_suite_focus=true#step:5:15 is one—I have `role-name` in skip_list (https://github.com/geerlingguy/ansible-role-php-xhprof/blob/master/.ansible-lint#L3), but when I run `molecule test` on it, it spits out the error that I should add `role-name` to my skip_list (even though it's already there).

to me this is the real bug at hand, that we cannot control this run of the linter at all, because it does not use our config file

**Comment by ssbarnea** [comment] 2022-03-10 18:21
@geerlingguy I checked with ansible-lint version from master (new pre-release very soon), and I was able to avoid your role-name issue by adding:
```
skip_list:
  - fqcn-builtins
mock_roles:
  - "geerlingguy.repo-remi"
  - "geerlingguy.php-versions"
  - "geerlingguy.php"
  - "geerlingguy.php-xhprof"
```

I will look into fixing molecule just after I finish the work with ansible-lint. 

```
$ ansible-lint -v
INFO     Set ANSIBLE_LIBRARY=/Users/ssbarnea/.cache/ansible-compat/84dc4c/modules:/Users/ssbarnea/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/Users/ssbarnea/.cache/ansible-compat/84dc4c/collections:/Users/ssbarnea/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/Users/ssbarnea/.cache/ansible-compat/84dc4c/roles:/Users/ssbarnea/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
WARNING  Loading custom .yamllint config file, this extends our internal yamllint config.
INFO     Discovered files to lint using: git ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git ls-files --deleted -z
INFO     Executing syntax check on molecule/default/converge.yml (0.59s)
```

**Comment by guerzon** [comment] 2022-05-19 09:57
Dear @ssbarnea,

I have been working on 'modernizing' some Ansible roles with `molecule` tests and ran into this issue.

Since this issue is still tagged as a 'bug', I guess at the least, it's accepted as one, right? Do we plan to fix it anytime soon?

```bash
(project-rl8) ➜  app git:(feature/rocky-linux8-support) ✗ molecule --version
molecule 3.6.1 using python 3.9 
    ansible:2.12.5
    delegated:3.6.1 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
    podman:2.0.0 from molecule_podman requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:1.0.0 from molecule_vagrant
(project-rl8) ➜  app git:(feature/rocky-linux8-support) ✗ ansible --version
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/Users/lester/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lester/.local/share/virtualenvs/project-rl8-IYDfrQpG/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/lester/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/lester/.local/share/virtualenvs/project-rl8-IYDfrQpG/bin/ansible
  python version = 3.9.11 (main, May 17 2022, 15:36:17) [Clang 13.1.6 (clang-1316.0.21.2.3)]
  jinja version = 3.1.2
  libyaml = True
(project-rl8) ➜  app git:(feature/rocky-linux8-support) ✗ pip freeze | grep compat
ansible-compat==2.0.4
(project-rl8) ➜  app git:(feature/rocky-linux8-support) ✗ 
```

I don't take issue on the opinionated naming conventions, it's true that it takes some work for us, but okay fine it has to be done even though we don't use galaxy.. but what's frustrating is that there was supposed to be a workaround but it doesn't work at all:

> As an alternative, you can add 'role-name' to either skip_list or warn_list.

Cheers,
Lester

**Comment by zhan9san** [comment] 2022-05-19 10:17
I'd like to look into this issue.

**Comment by ssbarnea** [comment] 2022-05-19 17:03
Please do

**Closed** 2022-05-23 15:51 UTC
Labels: bug

**Comment by briantist** [comment] 2022-05-23 17:36
@ssbarnea  #147 says it "partially" fixes this, seems like it makes a fix for this possible but doesn't implement one yet. Just flagging it because it seems like this being closed was unintentional (GitHub closing keywords).

**Comment by zhan9san** [comment] 2022-05-23 23:31
I am working on molecule side to fix it completely

**Comment by guerzon** [comment] 2022-06-11 07:20
Thanks everyone esp. @zhan9san for the fix!
