### ISSUE TITLE
Python 3.11: CollectionDependencyResolver() takes no arguments

### ISSUE THREAD

**Issue by dvzrv** [ansible/ansible-compat#229] opened 2023-04-08 22:14 UTC
Hi! We're currently doing the Python 3.11 rebuilds on Arch Linux.
Unfortunately it seems that ansible-compat now has a few more failing tests that I can't figure out:

test_prepare_environment_with_collections
test_require_collection_wrong_version
test_require_collection
test_install_collection
test_install_collection_dest
test_upgrade_collection
test_require_collection_no_cache_dir
test_install_collection_from_disk[normal]
test_install_collection_from_disk[deep]
test_runtime_example

```
=================================== FAILURES ===================================
__________________ test_prepare_environment_with_collections ___________________

tmp_path = PosixPath('/tmp/pytest-of-builduser/pytest-0/test_prepare_environment_with_0')

    def test_prepare_environment_with_collections(tmp_path: pathlib.Path) -> None:
        """Check that collections are correctly installed."""
        runtime = Runtime(isolated=True, project_dir=str(tmp_path))
>       runtime.prepare_environment(required_collections={"community.molecule": "0.1.0"})

test/test_runtime.py:164:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_dir/usr/lib/python3.11/site-packages/ansible_compat/runtime.py:385: in prepare_environment
    self.install_collection(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ansible_compat.runtime.Runtime object at 0x7f29d2001590>
collection = 'community.molecule:>=0.1.0'
destination = '/build/.cache/ansible-compat/5e37ff/collections', force = False

    def install_collection(
        self,
        collection: str,
        destination: Optional[Union[str, pathlib.Path]] = None,
        force: bool = False,
    ) -> None:
        """Install an Ansible collection.

        Can accept version constraints like 'foo.bar:>=1.2.3'
        """
        cmd = [
            "ansible-galaxy",
            "collection",
            "install",
            "-vvv",  # this is needed to make ansible display important info in case of failures
        ]
        if force:
            cmd.append("--force")

        # As ansible-galaxy install is not able to automatically determine
        # if the range requires a pre-release, we need to manuall add the --pre
        # flag when needed.
        matches = version_re.search(collection)
        if matches and Version(matches[1]).is_prerelease:
            cmd.append("--pre")

        if destination:
            cmd.extend(["-p", str(destination)])
        cmd.append(f"{collection}")

        _logger.info("Running from %s : %s", os.getcwd(), " ".join(cmd))
        run = self.exec(
            cmd,
            retry=True,
        )
        if run.returncode != 0:
            msg = f"Command returned {run.returncode} code:\n{run.stdout}\n{run.stderr}"
            _logger.error(msg)
>           raise InvalidPrerequisiteError(msg)
E           ansible_compat.errors.InvalidPrerequisiteError: Command returned 250 code:
E           ansible-galaxy [core 2.14.4]
E             config file = /etc/ansible/ansible.cfg
E             configured module search path = ['/build/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
E             ansible python module location = /usr/lib/python3.11/site-packages/ansible
E             ansible collection location = /build/.ansible/collections:/usr/share/ansible/collections
E             executable location = /usr/bin/ansible-galaxy
E             python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
E             jinja version = 3.1.2
E             libyaml = True
E           Using /etc/ansible/ansible.cfg as config file
E           Starting galaxy collection install process
E           Process install dependency map
E           the full traceback was:
E
E           Traceback (most recent call last):
E             File "/usr/lib/python3.11/site-packages/ansible/cli/__init__.py", line 647, in cli_executor
E               exit_code = cli.run()
E                           ^^^^^^^^^
E             File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 714, in run
E               return context.CLIARGS['func']()
E                      ^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 115, in method_wrapper
E               return wrapped_method(*args, **kwargs)
E                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1363, in execute_install
E               self._execute_install_collection(
E             File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1400, in _execute_install_collection
E               install_collections(
E             File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 730, in install_collections
E               dependency_map = _resolve_depenency_map(
E                                ^^^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1766, in _resolve_depenency_map
E               collection_dep_resolver = build_collection_dependency_resolver(
E                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/lib/python3.11/site-packages/ansible/galaxy/dependency_resolution/__init__.py", line 43, in build_collection_dependency_resolver
E               return CollectionDependencyResolver(
E                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           TypeError: CollectionDependencyResolver() takes no arguments
E
E           [WARNING]: The specified collections path '/build/.cache/ansible-
E           compat/5e37ff/collections' is not part of the configured Ansible collections
E           paths '/build/.ansible/collections:/usr/share/ansible/collections'. The
E           installed collection will not be picked up in an Ansible run, unless within a
E           playbook-adjacent collections directory.
E           ERROR! Unexpected Exception, this is probably a bug: CollectionDependencyResolver() takes no arguments

test_dir/usr/lib/python3.11/site-packages/ansible_compat/runtime.py:265: InvalidPrerequisiteError
------------------------------ Captured log call -------------------------------
WARNING  ansible_compat.runtime:runtime.py:188 Retrying execution failure 250 of: ansible-galaxy collection install -vvv -p /build/.cache/ansible-compat/5e37ff/collections community.molecule:>=0.1.0
ERROR    ansible_compat.runtime:runtime.py:264 Command returned 250 code:
ansible-galaxy [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/build/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /build/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map
the full traceback was:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/cli/__init__.py", line 647, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 714, in run
    return context.CLIARGS['func']()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 115, in method_wrapper
    return wrapped_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1363, in execute_install
    self._execute_install_collection(
  File "/usr/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1400, in _execute_install_collection
    install_collections(
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 730, in install_collections
    dependency_map = _resolve_depenency_map(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/collection/__init__.py", line 1766, in _resolve_depenency_map
    collection_dep_resolver = build_collection_dependency_resolver(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/galaxy/dependency_resolution/__init__.py", line 43, in build_collection_dependency_resolver
    return CollectionDependencyResolver(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CollectionDependencyResolver() takes no arguments

[WARNING]: The specified collections path '/build/.cache/ansible-
compat/5e37ff/collections' is not part of the configured Ansible collections
paths '/build/.ansible/collections:/usr/share/ansible/collections'. The
installed collection will not be picked up in an Ansible run, unless within a
playbook-adjacent collections directory.
ERROR! Unexpected Exception, this is probably a bug: CollectionDependencyResolver() takes no arguments

[... other errors skipped for brevity, more in logs below! ]

=============================== warnings summary ===============================
../../../../usr/lib/python3.11/site-packages/_pytest/cacheprovider.py:432
  /usr/lib/python3.11/site-packages/_pytest/cacheprovider.py:432: PytestCacheWarning: could not create cache path /dev/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../../../../usr/lib/python3.11/site-packages/_pytest/cacheprovider.py:386
  /usr/lib/python3.11/site-packages/_pytest/cacheprovider.py:386: PytestCacheWarning: could not create cache path /dev/.pytest_cache/v/cache/lastfailed
    config.cache.set("cache/lastfailed", self.lastfailed)

../../../../usr/lib/python3.11/site-packages/_pytest/stepwise.py:56
  /usr/lib/python3.11/site-packages/_pytest/stepwise.py:56: PytestCacheWarning: could not create cache path /dev/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ../../../../dev/test/test_runtime.py::test_prepare_environment_with_collections
FAILED ../../../../dev/test/test_runtime.py::test_require_collection_wrong_version
FAILED ../../../../dev/test/test_runtime.py::test_require_collection - ansibl...
FAILED ../../../../dev/test/test_runtime.py::test_install_collection - ansibl...
FAILED ../../../../dev/test/test_runtime.py::test_install_collection_dest - a...
FAILED ../../../../dev/test/test_runtime.py::test_upgrade_collection - ansibl...
FAILED ../../../../dev/test/test_runtime.py::test_require_collection_no_cache_dir
FAILED ../../../../dev/test/test_runtime.py::test_install_collection_from_disk[normal]
FAILED ../../../../dev/test/test_runtime.py::test_install_collection_from_disk[deep]
FAILED ../../../../dev/test/test_runtime_example.py::test_runtime_example - a...
=========== 10 failed, 68 passed, 2 deselected, 3 warnings in 29.03s ===========
```

[python-ansible-compat-3.0.1-2-x86_64-build.log](https://github.com/ansible/ansible-compat/files/11184313/python-ansible-compat-3.0.1-2-x86_64-build.log)
[python-ansible-compat-3.0.1-2-x86_64-check.log](https://github.com/ansible/ansible-compat/files/11184314/python-ansible-compat-3.0.1-2-x86_64-check.log)

Maybe you have any pointers as to what is happening here?

**Comment by ssbarnea** [comment] 2023-04-13 15:54
@dvzrv Can you reproduce this bug with a version of Ansible installed using pip? In this case, which one?

If Ansible comes installed from any other method, we might have to close the bug as wontfix. I am bit intrigued because we test it not only with current stable version but also with pre-releases of Ansible, so compat should work with a good range of ansible versions.

**Comment by dvzrv** [comment] 2023-04-13 17:14
I *think* I have found the culprit. The provided temporary installation path was provided as a relative path.
Adding it to PYTHONPATH as an absolute string fixed these errors with test_runtime*! :)

**Comment by ssbarnea** [comment] 2023-04-14 13:59
I was also able to get a VM with arch running, parallels did not work but UTM did and now I have a box where I could try to reproduce future reports, still you will need to provide commands I need to run as I don't really know how to use even the pacman.

I was even able to install ansible-lint via `pacman -Syu ansible-lint` but to my surprise the executable was not in path, so I do not know if it works or not.

**Closed by ssbarnea** 2023-04-14 13:59 UTC
Labels: help wanted

**Comment by dvzrv** [comment] 2023-04-14 17:05
> I could try to reproduce future reports, still you will need to provide commands I need to run as I don't really know how to use even the pacman.

That's cool! :smile_cat: 

If you install the following, you can start building packages the way we do there:
```shell
sudo pacman -Syu devtools asp
```
Afterwards you can download sources of any package using asp, e.g.:

```shell
asp checkout python-ansible-compat
```

If you go to the cloned dir, you can start building there:
```shell
# that dir is where the PKGBUILD (build script) file is
cd python-ansible-compat/trunk
extra-x86_64-build
```

The build scripts are mirrored to github, so e.g. the one for python-ansible-compat you can find here: https://github.com/archlinux/svntogit-community/blob/packages/python-ansible-compat/trunk/PKGBUILD

> I was even able to install ansible-lint via pacman -Syu ansible-lint but to my surprise the executable was not in path, so I do not know if it works or not.

That sounds rather weird. `/usr/bin/ansible-lint` should definitely be in `PATH`!

You could check that `/usr/bin` is in there with `echo $PATH`.
